'use client';
import dynamic from 'next/dynamic';
import {Suspense,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {Search,Wind,Eye,ClipboardPlus,Download,ShieldCheck,Check,GitCompareArrows,Info} from 'lucide-react';
import {useBundle,useScenarios,number,relativeTime,downloadJson,api,useApiStatus} from '@/lib/data';
import {useApp} from '@/lib/store';
import type {Model,WorkOrder} from '@/lib/types';
import {PageHeading,Panel,Stat,Status,Provenance,Notice,Loading,ErrorState} from '@/components/ui';
import {Chart,lineOption} from '@/components/charts';
import {Replay} from '@/components/replay';
const Cutaway=dynamic(()=>import('@/components/cutaway'),{ssr:false});
function Investigation(){const b=useBundle(),q=useScenarios(),status=useApiStatus();const state=useApp();const params=useSearchParams();const router=useRouter();const [tab,setTab]=useState<'evidence'|'compare'>(params.get('compare')?'compare':'evidence');const [subsystem,setSubsystem]=useState('gearbox');const [windowSize,setWindowSize]=useState(288);
 if(b.isPending||q.isPending)return <Loading/>;if(!b.data||!q.data)return <ErrorState message="Scenario evidence is unavailable." retry={()=>q.refetch()}/>;
 const asset=b.data.assets.find(a=>a.id===state.assetId)||b.data.assets[2];const scenario=q.data.find(s=>s.id===state.scenarioId)||q.data[0];const point=scenario.data[state.step];const start=Math.max(0,state.step-windowSize+1);const visible=scenario.data.slice(start,state.step+1);const labels=visible.map(v=>relativeTime(v.step));const alarm=scenario.alarms[state.model];const alarmed=alarm!==null&&state.step>=alarm;
 const order=async()=>{const existing=state.orders.find(o=>o.asset_id===asset.id&&o.status!=='Completed');if(existing){state.notify(`${existing.id} is already open for ${asset.id}.`);router.push('/tech/');return;}const work:WorkOrder={id:`WO-${Date.now().toString().slice(-7)}`,asset_id:asset.id,title:`Inspect ${subsystem.replaceAll('_',' ')}`,status:'Assigned',priority:alarmed?'High':'Medium',crew:'Crew 1',skill:'mechanical',duration_hours:4,notes:'Created from the simulated evidence view.',provenance:'Simulated',checklist:[{text:'Confirm permit and isolation with the site supervisor',done:false},{text:'Review sensor history and inspect the associated subsystem',done:false},{text:'Record findings and request supervisor review',done:false}]};if(status.data){try{await api('/workorders','POST',work);}catch{state.notify('Saved locally. The API could not synchronize this work order.');}}state.addOrder(work);state.notify(`Work order ${work.id} created.`);router.push('/tech/');};
 return <><PageHeading title="Follow the signal. Find the evidence." description="Understand a deviation before you dispatch a crew." actions={<><button className="button secondary" onClick={()=>downloadJson(`evidence-${asset.id}.json`,{provenance:'Simulated',scenario:scenario.id,step:state.step,point,training:scenario.training})}><Download size={14}/>Export evidence</button><button className="button primary" onClick={order}><ClipboardPlus size={14}/>Create work order</button></>}/>
 <div className="toolbar"><div className="toolbar-group"><Wind size={19}/><select aria-label="Investigated asset" value={asset.id} onChange={e=>state.selectAsset(e.target.value)}>{b.data.assets.filter(a=>a.type==='wind').map(a=><option key={a.id} value={a.id}>{a.id} · {a.name}</option>)}</select><Status value={alarmed?'Warning':state.step>100&&scenario.event_label?'Watch':'Healthy'}/><Provenance/></div><div className="toolbar-group"><span className="muted">Model</span><div className="model-buttons">{(['B0','M1','M2','M3'] as const).map(m=><button key={m} className={state.model===m?'active':m==='M1'||m==='M3'?'unavailable':''} aria-pressed={state.model===m} onClick={()=>m==='M1'||m==='M3'?state.notify(`${m} is awaiting trained model artifacts. No fabricated score will be displayed.`):state.setModel(m as Model)}>{m}{m==='M2'?' · Prototype':m==='M1'||m==='M3'?' · Pending':''}</button>)}</div></div></div>
 <Notice>This scenario is a Ridge normal-behavior prototype trained on synthetic observations. The measured LightGBM evaluation on real CARE turbine data is published on the Performance page. {asset.id!=='T-03'&&'This asset shows the normal illustrative window; the injected gearbox demonstration is on T-03.'}</Notice>
 <div className="section-gap panel"><div className="row-between panel-pad" style={{paddingBottom:12}}><div><h2>{scenario.name}</h2><p style={{fontSize:10,marginTop:4}}>Independent synthetic scenario · 10-minute observations</p></div><select aria-label="Replay scenario" value={state.scenarioId} onChange={e=>state.setScenario(e.target.value)}>{q.data.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div><Replay scenario={scenario}/></div>
 <div className="stats-strip section-gap"><Stat label="Gearbox temperature" value={`${point.gearbox_temperature.toFixed(1)}°C`} detail={`Expected ${point.expected_temperature.toFixed(1)}°C`}/><Stat label="Normalized deviation" value={`${point.residual.toFixed(1)}σ`} detail="Relative to training residual spread"/><Stat label="Criticality" value={`${point.criticality[state.model]} / ${scenario.threshold}`} detail="Net persistent anomalous points"/><div className="strip-caption"><ShieldCheck size={22}/><span>Evidence guides inspection.<br/>It does not prove a cause.</span></div></div>
 <div className="tab-nav"><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}><Search size={13}/> Evidence</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}><GitCompareArrows size={13}/> Compare periods</button></div>
 {tab==='evidence'?<><div className="content-grid"><div className="stack"><Panel title="Measured vs expected" subtitle="Temperature responds to both load and operating conditions." action={<select aria-label="Chart window" value={windowSize} onChange={e=>setWindowSize(+e.target.value)}><option value={288}>Full window</option><option value={144}>Last 24 hours</option><option value={36}>Last 6 hours</option></select>}><Chart label="Measured and expected gearbox temperature in degrees Celsius" option={lineOption(labels,[{name:'Measured',data:visible.map(v=>v.gearbox_temperature),color:'#ce703b'},{name:'Expected',data:visible.map(v=>v.expected_temperature),color:'#346b50',dashed:true}], '°C',state.model==='B0'?scenario.b0_upper:undefined)}/><p className="chart-caption">Source: scenarios.json · {scenario.id} · visible through {relativeTime(state.step)}</p></Panel><div className="two-columns"><Panel title="Residual" subtitle="Actual minus expected, normalized."><Chart height={180} label="Normalized residual" option={lineOption(labels,[{name:'Residual',data:visible.map(v=>v.residual),color:'#5c7e69',area:true}],'σ')}/></Panel><Panel title="Criticality counter" subtitle="Alarm after persistent net anomalies."><Chart height={180} label="Criticality and alarm threshold" option={lineOption(labels,[{name:state.model,data:visible.map(v=>v.criticality[state.model]),color:'#ce703b',area:true}],'points',72)}/></Panel></div></div><div className="stack"><Panel title="Subsystem view" subtitle="Select a component to connect the view to the evidence."><div className="cutaway-wrap"><Cutaway selected={subsystem} onSelect={setSubsystem}/></div><div className="panel-body" style={{paddingTop:12}}><span className="chip">Schematic nacelle cutaway</span><p style={{fontSize:10,marginTop:9}}>Highlighted: <strong>{subsystem.replaceAll('_',' ')}</strong>. Geometry is illustrative.</p></div></Panel><Panel title="Signals most associated with this deviation" subtitle="Association does not establish a root cause."><div className="signal-list">{[{label:'Gearbox temperature',sub:'gearbox',value:point.gearbox_temperature-point.expected_temperature},{label:'Main bearing temperature',sub:'main_bearing',value:point.bearing_temperature-(point.expected_temperature-10)},{label:'Generator temperature',sub:'generator',value:point.generator_temperature-(point.expected_temperature-6)}].map(s=><button className="signal-row" style={{width:'100%',textAlign:'left'}} key={s.label} onClick={()=>setSubsystem(s.sub)}><div><strong>{s.label}</strong><small>{s.sub.replaceAll('_',' ')} · raw deviation</small><div className="signal-meter"><i style={{width:`${Math.min(100,Math.abs(s.value)*5)}%`}}/></div></div><b>{s.value>=0?'+':''}{s.value.toFixed(1)}°C</b></button>)}</div></Panel></div></div>
 <Panel title="Anomaly score" subtitle={state.model==='B0'?'Raw training-percentile exceedance, before persistence filtering.':'Exponentially smoothed absolute residual from the synthetic normal-behavior prototype.'} className="section-gap"><Chart height={180} label="Anomaly score over time" option={lineOption(labels,[{name:`${state.model} score`,data:visible.map(v=>v.scores[state.model]),color:'#657e54',area:true}],'score',state.model==='M2'?3.5:.5)}/></Panel>
 <div className="two-columns section-gap"><Panel title="Main bearing vibration" subtitle="Velocity RMS, the classic mechanical wear channel."><Chart height={180} label="Main bearing vibration in millimetres per second" option={lineOption(labels,[{name:'Vibration',data:visible.map(v=>v.vibration),color:'#ce703b',area:true}],'mm/s')}/><p className="chart-caption">Simulated · excluded from every reported model metric. Shown because mechanical degradation is rarely visible in one channel alone.</p></Panel><Panel title="Phase current" subtitle="Grid-side output, tracked against rotor speed."><Chart height={180} label="Phase current in amperes and rotor speed in revolutions per minute" option={lineOption(labels,[{name:'Phase current (A)',data:visible.map(v=>v.phase_current),color:'#5c7e69'},{name:'Rotor speed (rpm ×100)',data:visible.map(v=>v.rotor_rpm*100),color:'#8a9a93',dashed:true}],'A')}/><p className="chart-caption">Simulated · rotor speed scaled ×100 to share one axis. Current following speed is normal; current falling while speed holds is not.</p></Panel></div>
 <div className="outcome section-gap"><Eye size={22}/>{state.revealed?<div><h3>{scenario.outcome}</h3><p>{scenario.outcome_index!==null?`${relativeTime(scenario.outcome_index)} · ${alarm!==null?number((scenario.outcome_index-alarm)/6,1)+' hours after the demonstration alarm':'No model alarm in this scenario'}.`:'The synthetic normal window contains no injected failure.'} This is an injected outcome, not a recorded equipment fault.</p></div>:<><div style={{flex:1}}><h3>The scenario outcome is hidden</h3><p>Investigate the signals first, then compare your conclusion with the injection.</p></div><button className="button secondary" onClick={state.reveal}>Reveal outcome</button></>}</div>
 </>:<><div className="two-columns">{q.data.slice().reverse().map(s=>{const data=s.data.slice(90,230);return <Panel key={s.id} title={s.event_label?'Injected degradation window':'Normal operating variation'} subtitle={s.event_label?'Equipment drift is intentionally added to the signal.':'Load and ambient conditions change naturally in the simulation.'}><Chart label={`${s.name} raw and expected values`} height={240} option={lineOption(data.map(v=>relativeTime(v.step)),[{name:'Measured',data:data.map(v=>v.gearbox_temperature),color:'#ce703b'},{name:'Expected',data:data.map(v=>v.expected_temperature),color:'#3e7554',dashed:true}],'°C')}/><Chart label={`${s.name} residual`} height={150} option={lineOption(data.map(v=>relativeTime(v.step)),[{name:'Residual',data:data.map(v=>v.residual),color:'#597b64',area:true}],'σ')}/><div className="panel-body"><div className="row-between"><span className="chip">B0: {s.alarms.B0===null?'No persistent alarm':'Alarm raised'}</span><span className="chip">Prototype: {s.alarms.M2===null?'No persistent alarm':'Alarm raised'}</span></div></div></Panel>;})}</div><Notice tone="warning">This contrast is designed into synthetic scenarios. It demonstrates how an expected-value model works, not that our system outperforms a baseline on real turbines. A genuine comparison must come from frozen held-out CARE events.</Notice></>}
 <div className="two-columns section-gap"><Panel title="Evidence quality"><div className="panel-body"><ul className="evidence-list"><li><Check size={12}/> Training and calibration are separated before scoring.</li><li><Check size={12}/> The temperature target is excluded from predictor inputs.</li><li><Info size={12}/> Vibration is simulated and excluded from model metrics.</li><li><Info size={12}/> No ARCANA/SHAP evidence or real fault label is claimed.</li></ul></div></Panel><Panel title="Recommended next step"><div className="panel-body"><p className="prose">The persistent temperature deviation is consistent with a change requiring inspection. Review oil and operating records, compare related sensors, and have the site team verify the equipment using approved procedures.</p><button className="button primary section-gap" onClick={order}><ClipboardPlus size={14}/>Create work order</button></div></Panel></div>
 </>;
}
export default function InvestigationPage(){return <Suspense fallback={<Loading/>}><Investigation/></Suspense>;}
